import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const facts=JSON.parse(await fs.readFile(path.join(root,'src/facts.json'),'utf8'));
const money=n=>n.toLocaleString('en-US');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const getStarted=`uv tool install 'harbor==0.18.0'\ngit clone https://github.com/GaugeForge/Quantum-Harbor\ncd Quantum-Harbor\ngit checkout ${facts.technical.repoCommit}\nuv sync\ndocker build -t qiqcbench-agent docker/agent/\nuv run python tools/build_qsim_images.py --tasks time_budgeted_hamlearn_10q\nharbor run -p harbor_tasks/time_budgeted_hamlearn_10q -a nop\nharbor view jobs`;
const navItems=[['task','Task'],['getting-started','Build'],['faq','FAQ']];
const email=(subject)=>`mailto:${facts.contact}?subject=${encodeURIComponent(subject)}`;
const svgIcon=async name=>(await fs.readFile(path.join(root,'src/assets',name+'.svg'),'utf8')).replace(/<!--[\s\S]*?-->/g,'').replace(/class="[^"]*"/,'').replace('<svg','<svg class="icon" aria-hidden="true" focusable="false"').replace(/>\s+</g,'><').replace(/\s*\n\s*/g,' ').trim();
const arrow=await svgIcon('arrow-up-right');
const arrowRight=await svgIcon('arrow-right');
const downloadIcon=await svgIcon('download');
const header=(documents=false)=>`<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="${documents?'index.html#overview':'#overview'}">GaugeForge<span aria-hidden="true">▍</span></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation" title="Open navigation"><img src="assets/menu.svg" alt=""></button><nav id="navigation" aria-label="Main navigation">${navItems.map(([id,label])=>`<a href="${documents?'index.html':''}#${id}">${label}</a>`).join('')}<a href="documents.html"${documents?' aria-current="page"':''}>Documents</a></nav></header>`;
const faqs=[
 ['Who can enter?','Individuals and teams of up to three people. There is no academic or professional qualification requirement. Applicable law and valid consent still apply.'],
 ['What exactly am I building?','An agent harness: the code that plans work, invokes tools, manages experiment state and verifies results around a fixed Hunyuan 4 Preview (HY4) model. You may modify an existing harness or build your own.'],
 ['Is registration open?',facts.links.registration?'Yes. Use the registration form to join the challenge.':'The registration form is to be announced. Use the participation email link to ask the organizer for information. An email inquiry does not register a team.'],
 ['Are model credits unlimited?','The event model is Tencent Hunyuan 4 Preview (HY4). Exact API quota and development allowance are to be announced. Each team has at most three official full benchmark evaluations.'],
 ['How is the Challenger Award different?','USD 15,000 goes only to the strict first qualifying Hunyuan 4 Preview (HY4) team to exceed the GPT-6 Astra baseline on the hidden leaderboard. If no team exceeds it, the award is not paid. Timestamp, baseline and stacking details will be frozen before registration.'],
 ['Are hidden tasks guaranteed uncontaminated?','No. Public paper tasks and repository material are already accessible. Hidden means withheld during evaluation, not proven absent from training data. Evaluation uses recorded evidence and controlled conditions.'],
 ['Do I need quantum hardware?','No. Quantum-Harbor provides a simulated laboratory. Real-hardware access is not part of the announced competition.'],
 ['What must I open source?','Submitted harness code is required to be AGPL open source. The exact version and release timing will be frozen before registration. Data and trajectory use has separate terms, including named organizer and partner recipients.'],
 ['Where are submissions uploaded?','The event submission interface is not yet released. The public repository supports local task runs. The participant guide labels the proposed competition package separately.']
];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Build an agent harness around Hunyuan 4 Preview for verified quantum engineering. QIQC Challenge by GaugeForge starts ${facts.schedule.start.label}."><meta name="theme-color" content="#f5f7f8"><title>QIQC Challenge | GaugeForge</title><link rel="stylesheet" href="styles.css"></head><body>
${header()}
<main id="main">
<section class="hero-stage" id="overview" aria-labelledby="hero-title"><div class="hero">
<div class="hero-field" id="rabi-lab" aria-hidden="true"><img class="field-fallback" src="assets/rabi-calibration.webp" alt=""><canvas id="rabi-canvas"></canvas></div>
<svg class="rabi-axes" viewBox="0 0 864 331.2" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width=".7"><path d="M32 0V286.2H864"/><path d="M32.0 286.2v4"/><path d="M150.85714285714286 286.2v4"/><path d="M269.7142857142857 286.2v4"/><path d="M388.57142857142856 286.2v4"/><path d="M507.42857142857144 286.2v4"/><path d="M626.2857142857143 286.2v4"/><path d="M745.1428571428571 286.2v4"/><path d="M864.0 286.2v4"/><path d="M28 262.35h4"/><path d="M28 202.725h4"/><path d="M28 143.1h4"/><path d="M28 83.47500000000001h4"/><path d="M28 23.849999999999994h4"/></g><g fill="currentColor" font-size="10" text-anchor="middle"><text x="32.0" y="302">0.0</text><text x="150.85714285714286" y="302">0.5</text><text x="269.7142857142857" y="302">1.0</text><text x="388.57142857142856" y="302">1.5</text><text x="507.42857142857144" y="302">2.0</text><text x="626.2857142857143" y="302">2.5</text><text x="745.1428571428571" y="302">3.0</text><text x="864.0" y="302">3.5</text><text x="21" y="265.35">-2</text><text x="21" y="205.725">-1</text><text x="21" y="146.1">0</text><text x="21" y="86.47500000000001">1</text><text x="21" y="26.849999999999994">2</text><text x="448" y="323">Pulse duration / Rabi period</text><text transform="translate(10 143) rotate(-90)">Detuning / drive strength</text></g></svg>
<div class="field-caption protected" id="rabi-caption"><p>RABI OSCILLATIONS</p><span>Pulse duration × detuning · ideal two-level model</span><div><span>Illustration, not experimental data</span><button id="rabi-play" type="button" aria-label="Pause background animation">Ⅱ &nbsp; Pause motion</button></div></div>
<div class="hero-inner wrap">
<div class="hero-copy">
<h1 id="hero-title" class="protected"><span class="title-line"><span class="motion-surface">Agentic Quantum</span></span> <span class="title-line"><span class="motion-surface"><em>Coding Challenge</em></span></span></h1>
<p class="event-intro protected"><span class="intro-line">An online challenge to build AI agents for quantum engineering.</span><span class="intro-line">Design your harness around Hunyuan 4 Preview and put it to the test.</span></p>
<p class="hero-slogan protected"><mark>${facts.messaging.hook}</mark></p>
</div>
<section class="entry-basics" aria-label="Participation essentials">
<div class="entry-details"><div class="entry-register">${facts.links.registration?`<a class="button primary register-now" href="${facts.links.registration}" target="_blank" rel="noopener">Register now ${arrow}</a>`:`<button class="button primary register-now" id="register-now" type="button" aria-haspopup="dialog">Register now ${arrow}</button>`}<span>${facts.links.registration?'Join the challenge.':'Registration form coming soon.'}</span><a class="button register-now rules-pdf" href="downloads/participant-guide.pdf" target="_blank" rel="noopener" aria-label="View Participant Guide (opens in a new tab)">View Participant Guide</a></div></div>
<div class="prize-overview"><article><span class="rule-label">PLACEMENT PRIZE POOL</span><h3 aria-label="USD ${money(facts.prizes.placesTotal)}"><span aria-hidden="true">USD <span class="prize-number" data-amount="${facts.prizes.placesTotal}" style="--number-width:${money(facts.prizes.placesTotal).length}ch">${money(facts.prizes.placesTotal)}</span></span></h3><p>Total across the five placement awards.</p></article><article class="challenger-prize"><span class="rule-label">THE CHALLENGER AWARD</span><h3 aria-label="USD ${money(facts.prizes.challengerAmount)}"><span aria-hidden="true">USD <span class="prize-number" data-amount="${facts.prizes.challengerAmount}" style="--number-width:${money(facts.prizes.challengerAmount).length}ch">${money(facts.prizes.challengerAmount)}</span></span></h3><p>Only the <strong>strict first team</strong> to exceed GPT-6 Astra on the hidden leaderboard.<br>If nobody exceeds it, the award is not paid.</p></article></div>
<div id="timeline" class="entry-timeline"><span class="basic-label">TIMELINE <small id="timeline-status" class="timeline-status">Date progress</small></span><div class="timeline-body"><div class="timeline-rail"><span class="timeline-timezone">UTC+8</span><div class="timeline-progress" role="progressbar" aria-label="Progress from competition start to Demo Day" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" aria-describedby="timeline-status" data-start="${facts.schedule.start.date}" data-deadline="${facts.schedule.deadline.date}" data-end="${facts.schedule.demo.date}"><span class="timeline-progress-fill"></span></div><span class="timeline-current" data-edge="start"><span class="timeline-status-dot" aria-hidden="true"></span></span></div><ol>${[['start','Competition begins'],['deadline','Submission deadline'],['demo','Demo Day']].map(([key,label])=>`<li><span class="timeline-event">${label}</span><time datetime="${facts.schedule[key].date}">NOV ${facts.schedule[key].date.slice(-2)}</time></li>`).join('')}</ol></div></div>
</section>
</div>
</div></section>
<section class="section task-section" id="task" aria-labelledby="task-title"><div class="wrap">
<div class="section-heading heading-split"><h2 id="task-title" class="section-title">Task</h2></div>
<p class="task-goal">Every team uses the same <strong>Tencent Hunyuan 4 Preview (HY4)</strong> model.<br>Your goal is to improve the <strong>harness</strong> around it: how the agent plans experiments, uses tools, learns from evidence and produces reliable solutions to quantum engineering tasks.</p>
<div class="task-layout">
<div class="task-copy"><h3>What your agent must do</h3><p>QIQCBench presents engineering problems in Quantum-Harbor, a simulated quantum laboratory. Your agent reads the task, chooses experiments within its resource budget, interprets the measurements and submits an answer that a separate verifier can check.</p>
<ul class="task-examples"><li><strong>Characterize a system.</strong><br>Estimate an unknown Hamiltonian or predict quantum correlations.</li><li><strong>Calibrate an experiment.</strong><br>Tune a controlled-Z pulse or a logical-CNOT decoder.</li><li><strong>Design measurements.</strong><br>Estimate molecular energy and its uncertainty.</li></ul>
<div class="task-split"><span><strong>${facts.rules.publicTasks}</strong> public practice tasks</span><span><strong>${facts.rules.eventTaskCount-facts.rules.publicTasks}</strong> hidden evaluation tasks</span></div>
</div>
<div class="task-interactive"><h3 class="task-step-hint">Explore a task, step by step.</h3>
<div class="task-steps" role="tablist" aria-label="Task stages">${['Understand','Plan','Experiment','Verify'].map((name,i)=>`<button id="task-step-${i}" type="button" role="tab" data-task-step="${i}" aria-controls="task-panel" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}"><span class="task-step-number">${i+1}</span><span>${name}</span></button>`).join('')}</div>
<div id="task-panel" class="task-panel" role="tabpanel" aria-labelledby="task-step-0" tabindex="0" aria-live="polite" aria-atomic="true">
<h4 id="task-stage-title">Understand the objective.</h4><p id="task-stage-copy">Read the task instructions and device specifications. Identify the quantity to estimate or the operation to calibrate, the available tools and the limits on experiments.</p>
<div class="task-schematic" aria-hidden="true"><span id="task-node-a">Task brief</span>${arrowRight}<span id="task-node-b">Tools &amp; limits</span>${arrowRight}<span id="task-node-c">Success criteria</span></div>
<p id="task-stage-outcome" class="task-outcome">Start with a clear target and an experiment budget.</p>
</div>
</div></div>
<div class="research-line"><a href="${facts.links.paper}">Read the paper ${arrow}</a><a href="${facts.links.benchmark}">Explore the benchmark ${arrow}</a></div>
</div></section>
<section class="section wrap" id="getting-started"><div class="section-heading"><h2 class="section-title">Build</h2><p>Docker, uv, git and Python 3.11+. On Windows, use Linux containers through WSL2. The no-key check below tests the public environment.</p></div><div class="terminal"><div class="terminal-bar"><span>Quantum-Harbor / Harbor 0.18.0</span><button id="copy-code" title="Copy installation commands" aria-label="Copy installation commands"><img src="assets/copy.svg" alt=""></button></div><pre><code id="install-code">${esc(getStarted)}</code></pre></div><p id="copy-status" role="status" class="small"></p><p class="note"><strong>Expected result: reward 0.</strong> The <code>nop</code> agent performs no science. This is an installation check, not an official entry.</p><p>The public repository includes example agent configurations. The competition Hunyuan 4 Preview adapter, exact model ID and upload service are to be announced. The current examples must not be presented as a working event integration.</p><div class="actions"><a class="button primary" href="${facts.links.repository}">Open Quantum-Harbor ${arrow}</a><a class="text-link" href="${facts.links.repository}/blob/${facts.technical.repoCommit}/docs/getting-started/installation.md">Installation reference ${arrow}</a></div></section>
<section class="section partners-section" id="partners"><div class="wrap"><h2 class="section-title">Partners</h2><div class="partner-content"><p>Hosted by <strong>GaugeForge</strong>. Community distribution, expert review, model support and post-event experiments are available ways to contribute.</p><p>External partners will be announced after confirmation. No external organization is currently listed as a confirmed event partner.</p></div><div class="actions"><a class="text-link" href="downloads/partner-handbook.pdf" target="_blank" rel="noopener" aria-label="View Partner Handbook PDF (opens in a new tab)">View Partner Handbook PDF ${arrow}</a></div></div></section>
<section class="section wrap" id="faq"><div class="section-heading"><h2 class="section-title">FAQ</h2></div><div class="faq">${faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>
<section class="participate-band" aria-labelledby="contact-title"><div class="wrap"><h2 id="contact-title">More questions? Email us.</h2><a class="contact" href="mailto:${facts.contact}">${facts.contact}</a><p class="small">Email inquiry only. Your mail application opens; nothing is sent automatically.</p></div></section></main>
${facts.links.registration?'':`<dialog id="registration-dialog" aria-labelledby="registration-title" aria-describedby="registration-description"><button type="button" class="dialog-close" aria-label="Close registration information">×</button><p class="eyebrow">QIQC CHALLENGE / REGISTRATION</p><h2 id="registration-title">Join the challenge.</h2><p id="registration-description">The official registration form is coming soon. Contact GaugeForge for participation information in the meantime.</p><a class="button primary" href="${email('QIQC Challenge registration inquiry')}">Contact the organizer ${arrow}</a><p class="dialog-note">An email inquiry does not register a team. Nothing is submitted automatically.</p></dialog>`}
<div class="footer-shell"><footer class="site-footer wrap"><a class="brand" href="#overview">GaugeForge<span aria-hidden="true">▍</span></a><p>QIQC Challenge / ${facts.version}</p><p>No registration data is collected on this site. Inquiries are handled by GaugeForge.<br>Data rights and the final participant privacy notice will be available before registration.</p><a href="downloads/participant-guide.html">Privacy and participant terms</a></footer></div><script src="shared.js" defer></script><script src="app.js" defer></script></body></html>`;
await fs.writeFile(path.join(root,'src/index.html'),html);

// Downloadable guide formats; HTML remains an online reading option.
const documents=[
 {slug:'participant-guide',title:'Participant Guide',description:'Eligibility, tasks, evaluation, prizes, submission requirements and participant terms.'},
 {slug:'partner-handbook',title:'Partner Handbook',description:'Event overview, partnership opportunities and ways to support the challenge.'}
];
const supplementaryMaterials=[
 {title:'QIQCBench',url:facts.links.benchmark,description:'Explore the benchmark behind the challenge and the quantum engineering tasks your harness will solve.'},
 {title:'QIQCBench research paper',url:facts.links.paper,description:'Read the research behind the benchmark for context on its tasks, evaluation methods and reported agent results.'},
 {title:'Quantum-Harbor',url:facts.links.repository,description:'Use the simulated quantum laboratory and public tasks to develop and practice with your agent harness.'},
 {title:'Installation reference',url:`${facts.links.repository}/blob/${facts.technical.repoCommit}/docs/getting-started/installation.md`,description:'Set up the local environment used in the challenge’s Build section before running practice tasks.'}
];
const documentsHtml=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Download the QIQC Challenge participant guide and partner handbook."><meta name="theme-color" content="#f5f7f8"><title>Documents | QIQC Challenge</title><link rel="stylesheet" href="styles.css"></head><body class="documents-page">
${header(true)}
<main id="main" class="documents-main wrap">
<a class="documents-back" href="index.html#overview">Back to the challenge</a>
<div class="documents-heading"><h1 class="section-title">Documents</h1><p>Guides and reference documents for the QIQC Challenge.</p></div>
<div class="document-list">${documents.map(doc=>`<article class="document-item" aria-labelledby="${doc.slug}-title"><div class="document-copy"><h2 id="${doc.slug}-title">${doc.title}</h2><p>${doc.description}</p><a class="text-link" href="downloads/${doc.slug}.html" target="_blank" rel="noopener">Read online ${arrow}</a></div><div class="document-downloads" aria-label="${doc.title} downloads">${[['pdf','PDF'],['md','Markdown']].map(([ext,label])=>`<a class="button document-download" href="downloads/${doc.slug}.${ext}" download aria-label="Download ${doc.title} (${label})">Download ${label} ${downloadIcon}</a>`).join('')}</div></article>`).join('')}</div>
<p class="documents-edition">Document edition · ${facts.version}</p>
<section class="supplementary-materials" aria-labelledby="supplementary-title">
<h2 id="supplementary-title" class="section-title">Supplementary materials</h2>
<p class="supplementary-intro">These GaugeForge resources provide the research background, benchmark and development tools used in the challenge.</p>
<div class="supplementary-grid">${supplementaryMaterials.map(item=>`<article class="supplementary-item"><h3><a href="${item.url}" target="_blank" rel="noopener">${item.title} ${arrow}</a></h3><p>${item.description}</p></article>`).join('')}</div>
</section>
</main><div class="footer-shell"><footer class="site-footer wrap"><a class="brand" href="index.html#overview">GaugeForge<span aria-hidden="true">▍</span></a><p>QIQC Challenge / ${facts.version}</p></footer></div><script src="shared.js" defer></script></body></html>`;
await fs.writeFile(path.join(root,'src/documents.html'),documentsHtml);

await fs.writeFile(path.join(root,'src/404.html'),'<!doctype html><html lang="en"><meta charset="utf-8"><title>Page not found | QIQC</title><link rel="stylesheet" href="styles.css"><h1>Page not found</h1><a href="/">Return to QIQC Challenge</a></html>');
await fs.writeFile(path.join(root,'src/_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Content-Security-Policy: default-src \'self\'; img-src \'self\' data:; style-src \'self\' \'unsafe-inline\'; script-src \'self\'; object-src \'none\'; base-uri \'self\'; form-action \'none\'\n');
